export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'about', title: 'About' },
    { name: 'contact', title: 'Contact' },
    { name: 'footer', title: 'Footer' },
    { name: 'social', title: 'Social Links' },
  ],
  fields: [
    {
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroCtaText',
      title: 'Hero CTA Text',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroImages',
      title: 'Hero Slideshow Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      group: 'hero',
    },
    {
      name: 'aboutDesignerHeading',
      title: 'About Section Heading',
      type: 'string',
      group: 'about',
    },
    {
      name: 'aboutName',
      title: 'Designer Name',
      type: 'string',
      group: 'about',
    },
    {
      name: 'aboutDescription1',
      title: 'Bio (Paragraph 1)',
      type: 'text',
      group: 'about',
    },
    {
      name: 'aboutDescription2',
      title: 'Bio (Paragraph 2)',
      type: 'text',
      group: 'about',
    },
    {
      name: 'aboutCtaText',
      title: 'About CTA Text',
      type: 'string',
      group: 'about',
    },
    {
      name: 'aboutImage',
      title: 'About Photo',
      type: 'image',
      options: { hotspot: true },
      group: 'about',
    },
    {
      name: 'contactTitle',
      title: 'Contact Title',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'location',
      title: 'Location',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'footerTagline',
      title: 'Footer Tagline',
      type: 'text',
      group: 'footer',
    },
    {
      name: 'copyright',
      title: 'Copyright Text',
      type: 'string',
      group: 'footer',
    },
    {
      name: 'socialInstagram',
      title: 'Instagram URL',
      type: 'url',
      group: 'social',
    },
    {
      name: 'socialLinkedin',
      title: 'LinkedIn URL',
      type: 'url',
      group: 'social',
    },
    {
      name: 'socialTelegram',
      title: 'Telegram URL',
      type: 'url',
      group: 'social',
    },
    {
      name: 'socialTiktok',
      title: 'TikTok URL',
      type: 'url',
      group: 'social',
    },
  ],
  preview: {
    prepare: () => ({ title: 'Site Settings' }),
  },
};
